hello.out:main.o student_average.o student_get_score.o student_input.o student_print.o 
	gcc main.o student_average.o student_get_score.o student_input.o student_print.o -o hello.out
main.o:main.c
	gcc -c main.c
student_average.o:student_average.c
	gcc -c student_average.c
student_get_score.o:student_get_score.c
	gcc -c student_get_score.c
student_input.o:student_input.c
	gcc -c student_input.c
student_print.o:student_print.c
	gcc -c student_print.c
